//
//  QUICTrustTests.swift
//  AMSMB2
//
//  Created by Amir Abbas on 24/07/2026.
//  Copyright © 2026 Mousavian. Distributed under MIT license.
//  All rights reserved.
//

#if canImport(Network)

import Foundation
import Security
import XCTest
@testable import AMSMB2

@available(iOS 15, macOS 12, macCatalyst 15, tvOS 15, watchOS 8, visionOS 1, *)
final class QUICTrustTests: XCTestCase, @unchecked Sendable {
    // MARK: - resolveTrust (design D5 fail-closed)

    /// `.system` resolves to `.system` (no anchors, no verify block installed downstream).
    func testResolveSystemTrust() throws {
        guard case .system = try QUICTransportApple.resolveTrust(.system, host: "fs.example.com") else {
            return XCTFail("expected .system")
        }
    }

    /// `.insecureNoVerification` resolves to `.insecure`.
    func testResolveInsecureTrust() throws {
        guard case .insecure = try QUICTransportApple.resolveTrust(.insecureNoVerification, host: "h") else {
            return XCTFail("expected .insecure")
        }
    }

    /// `.customRoots` with invalid DER fails closed with `EINVAL` before any connection exists.
    func testResolveCustomRootsInvalidDERThrowsEINVAL() {
        let policy = SMBQUICConfiguration.TrustPolicy.customRoots([Data([0x00, 0x01, 0x02])])
        XCTAssertThrowsError(try QUICTransportApple.resolveTrust(policy, host: "h")) { error in
            XCTAssertEqual((error as? POSIXError)?.code, .EINVAL)
        }
    }

    /// `.customRoots([])` (empty anchor set) fails closed with `EINVAL`.
    func testResolveCustomRootsEmptyThrowsEINVAL() {
        XCTAssertThrowsError(try QUICTransportApple.resolveTrust(.customRoots([]), host: "h")) { error in
            XCTAssertEqual((error as? POSIXError)?.code, .EINVAL)
        }
    }

    /// A valid DER anchor resolves to `.customRoots` carrying exactly that anchor and the host.
    func testResolveCustomRootsValidDER() throws {
        guard let der = Self.selfSignedDER(commonName: "quic.test") else {
            throw XCTSkip("openssl unavailable — cannot generate a test certificate")
        }
        guard case .customRoots(let anchors, let host) = try QUICTransportApple.resolveTrust(
            .customRoots([der]), host: "quic.test"
        ) else {
            return XCTFail("expected .customRoots")
        }
        XCTAssertEqual(anchors.count, 1)
        XCTAssertEqual(host, "quic.test")
    }

    // MARK: - evaluateCustomRootsTrust (design D5 steps 3–6)

    /// Custom root with the correct hostname: the self-signed leaf as its own anchor evaluates to
    /// trusted; wrong hostname is rejected (custom roots never disable hostname verification); an
    /// unrelated anchor is rejected (anchors REPLACE system roots — no augmentation).
    func testEvaluateCustomRootsMatrix() throws {
        guard
            let leafDER = Self.selfSignedDER(commonName: "quic.test"),
            let otherDER = Self.selfSignedDER(commonName: "other.test")
        else {
            throw XCTSkip("openssl unavailable — cannot generate test certificates")
        }
        let leaf = try Self.certificate(leafDER)
        let other = try Self.certificate(otherDER)

        // Correct hostname, self-signed leaf as its own anchor → trusted.
        XCTAssertTrue(
            QUICTransportApple.evaluateCustomRootsTrust(
                Self.serverTrust([leaf]), host: "quic.test", anchors: [leaf]
            ),
            "custom root with matching hostname must validate"
        )

        // Wrong hostname → rejected (hostname verification stays enforced).
        XCTAssertFalse(
            QUICTransportApple.evaluateCustomRootsTrust(
                Self.serverTrust([leaf]), host: "wrong.test", anchors: [leaf]
            ),
            "custom roots must not disable hostname verification"
        )

        // System-root / unrelated anchor → rejected (anchors replace, not augment).
        XCTAssertFalse(
            QUICTransportApple.evaluateCustomRootsTrust(
                Self.serverTrust([leaf]), host: "quic.test", anchors: [other]
            ),
            "a chain that does not anchor to the supplied roots must be rejected"
        )
    }

    // MARK: - Certificate helpers

    /// Builds a `SecCertificate` from DER, or throws if the bytes are not a certificate.
    private static func certificate(_ der: Data) throws -> SecCertificate {
        guard let certificate = SecCertificateCreateWithData(nil, der as CFData) else {
            throw XCTSkip("generated bytes were not a valid certificate")
        }
        return certificate
    }

    /// A server `SecTrust` over `certificates` with the basic X.509 policy — the D5 helper then
    /// installs the SSL hostname policy and anchors itself.
    private static func serverTrust(_ certificates: [SecCertificate]) -> SecTrust {
        var trust: SecTrust?
        SecTrustCreateWithCertificates(
            certificates as CFArray, SecPolicyCreateBasicX509(), &trust
        )
        return trust!
    }

    /// Generates a temporally-valid self-signed leaf (CA:FALSE, `serverAuth` EKU, matching SAN)
    /// via `openssl` and returns its DER bytes, or `nil` when `openssl` is unavailable/failed.
    static func selfSignedDER(commonName: String) -> Data? {
        let directory = FileManager.default.temporaryDirectory
        let base = directory.appendingPathComponent("amsmb2-quic-\(UUID().uuidString)")
        let keyPath = base.appendingPathExtension("key").path
        let pemPath = base.appendingPathExtension("pem").path
        defer {
            try? FileManager.default.removeItem(atPath: keyPath)
            try? FileManager.default.removeItem(atPath: pemPath)
        }

        let process = Process()
        process.executableURL = URL(fileURLWithPath: "/usr/bin/env")
        process.arguments = [
            "openssl", "req", "-x509", "-newkey", "rsa:2048", "-nodes",
            "-keyout", keyPath, "-out", pemPath, "-days", "300",
            "-subj", "/CN=\(commonName)",
            "-addext", "subjectAltName=DNS:\(commonName)",
            "-addext", "basicConstraints=critical,CA:FALSE",
            "-addext", "extendedKeyUsage=serverAuth",
        ]
        process.standardOutput = FileHandle.nullDevice
        process.standardError = FileHandle.nullDevice

        do {
            try process.run()
        } catch {
            return nil
        }
        process.waitUntilExit()
        guard process.terminationStatus == 0,
              let pem = try? String(contentsOfFile: pemPath, encoding: .utf8)
        else {
            return nil
        }
        return pemToDER(pem)
    }

    /// Extracts the first certificate block from PEM text and decodes it to DER.
    private static func pemToDER(_ pem: String) -> Data? {
        let begin = "-----BEGIN CERTIFICATE-----"
        let end = "-----END CERTIFICATE-----"
        guard let beginRange = pem.range(of: begin),
              let endRange = pem.range(of: end, range: beginRange.upperBound..<pem.endIndex)
        else {
            return nil
        }
        let body = pem[beginRange.upperBound..<endRange.lowerBound]
            .split(whereSeparator: \.isNewline)
            .joined()
        return Data(base64Encoded: body)
    }
}

#endif // canImport(Network)
