[global]
   workgroup = WORKGROUP
   server string = AMSMB2 Test SMB
   security = user
   log level = 1
   unix extensions = yes
   allow insecure wide links = yes

[testshare]
   path = /share
   browseable = yes
   read only = no
   valid users = testuser
   create mask = 0644
   directory mask = 0755
   wide links = yes
   follow symlinks = yes
   vfs objects = streams_xattr
